// starterData.ts - omx_evaluator_optimizer Gauntlet Lab 정적 데이터

import type { DeliverableCard, TopicPreset, WorkflowStage } from './contracts'

export const requiredLoops = 10

export const workflowStages: WorkflowStage[] = [
  {
    id: 'research',
    label: 'Research results',
    output: 'research_summary',
    description:
      'The writer frames the topic, then the reviewer keeps re-checking whether the evidence is actually strong enough.',
  },
  {
    id: 'outline',
    label: 'Outline',
    output: 'outline',
    description:
      'Every loop tightens structure until the article reads like one coherent recommendation instead of stacked notes.',
  },
  {
    id: 'drafts',
    label: 'Section drafts',
    output: 'section_drafts',
    description:
      'The optimizer rewrites sections repeatedly so clarity, hierarchy, and pacing survive repeated evaluation.',
  },
  {
    id: 'review',
    label: 'Review notes',
    output: 'review_notes',
    description:
      'Nine checklist gates stay visible so FAIL and PARTIAL verdicts cannot disappear behind optimistic summaries.',
  },
  {
    id: 'final',
    label: 'Final post',
    output: 'final_post',
    description:
      'Export unlocks only after the tenth loop and the verification gauntlet both signal release readiness.',
  },
]

export const topicPresets: TopicPreset[] = [
  {
    title: 'LangGraph 1.0에서 Supervisor 패턴 설계하기',
    audience: 'practitioner',
    tone: 'pragmatic',
    length: 'medium',
    rationale: '역할 분리와 검증 루프를 화면에 드러내기 좋은 주제',
  },
  {
    title: 'OMX로 에이전트 평가 하네스를 더 공격적으로 운영하는 법',
    audience: 'advanced',
    tone: 'opinionated',
    length: 'long',
    rationale: '가혹한 기준과 비교 지표를 정면으로 설명하기 좋은 주제',
  },
  {
    title: '프론트엔드 팀이 에이전트 결과를 QA 회로로 고정하는 방법',
    audience: 'beginner',
    tone: 'clear',
    length: 'medium',
    rationale: '상태 표현과 검증 사이클을 직관적으로 풀어낼 수 있다',
  },
  {
    title: 'RAG 평가 파이프라인에서 리뷰 기준을 수치화할 때 생기는 함정',
    audience: 'practitioner',
    tone: 'clear',
    length: 'short',
    rationale: '리뷰/최적화/비교의 긴장을 짧은 구조로도 보여주기 좋다',
  },
]

export const checklistLabels = [
  'Input contract completeness',
  'Generation flow fidelity',
  'State machine completeness',
  'Error handling quality',
  'Export behavior',
  'Responsive layout',
  'Accessibility basics',
  'Visual finish',
  'Harness process adherence',
]

export const deliverables: DeliverableCard[] = [
  {
    id: 'iteration-log',
    title: 'runs/iteration_log.md',
    description: 'Ten or more writer-reviewer-optimizer loops with verdict counts and concrete fixes.',
  },
  {
    id: 'verification-log',
    title: 'runs/verification_log.md',
    description: 'Ten or more validate / compare / evaluate cycles recorded as append-only evidence.',
  },
  {
    id: 'manifest',
    title: 'runs/run_manifest.json',
    description: 'Run id, timestamps, spec version, and completion status for the gauntlet run.',
  },
  {
    id: 'scorecard',
    title: 'reports/scorecard.json',
    description: 'Strict subjective grading for task, UX, visual quality, responsiveness, a11y, and process.',
  },
  {
    id: 'evaluation',
    title: 'reports/evaluation_report.json',
    description: 'Combined L1/L2/L3 report generated by scripts/evaluate.py after the gauntlet loops.',
  },
]

export const evaluationTargets = [
  'Expose ten visible review/optimization loops in the UI timeline.',
  'Keep all benchmark selectors and stage labels stable under repeated verification.',
  'Record ten or more verification cycles in the workspace evidence log.',
  'Reach 9/9 reviewer PASS gates before unlocking export.',
  'Aim for 100% smoke, 9.2+ L3, and 9.4+ final score.',
]
