// starterData.ts - evaluator_optimizer Loop Lab 정적 데이터

import type { DeliverableCard, TopicPreset, WorkflowStage } from './contracts'

export const workflowStages: WorkflowStage[] = [
  {
    id: 'research',
    label: 'Research results',
    output: 'research_summary',
    description: 'The writer frames the topic, the reviewer challenges weak claims, and the optimizer tightens the evidence.',
  },
  {
    id: 'outline',
    label: 'Outline',
    output: 'outline',
    description: 'The loop stabilizes section order and clarifies what each section must prove.',
  },
  {
    id: 'drafts',
    label: 'Section drafts',
    output: 'section_drafts',
    description: 'Every iteration rewrites the draft so the article sounds less like notes and more like an argument.',
  },
  {
    id: 'review',
    label: 'Review notes',
    output: 'review_notes',
    description: 'A strict reviewer scores nine checklist items and tells the optimizer what still blocks release.',
  },
  {
    id: 'final',
    label: 'Final post',
    output: 'final_post',
    description: 'Only the last loop can unlock export-ready Markdown for the release candidate.',
  },
]

export const topicPresets: TopicPreset[] = [
  {
    title: 'LangGraph 1.0에서 Supervisor 패턴 설계하기',
    audience: 'practitioner',
    tone: 'pragmatic',
    length: 'medium',
    rationale: '역할 경계, 반복 검증, release criteria를 설명하기 좋은 주제',
  },
  {
    title: 'React Compiler 시대의 memoization 전략',
    audience: 'advanced',
    tone: 'opinionated',
    length: 'short',
    rationale: '거친 초안에서 명확한 주장으로 다듬는 과정을 보여주기 좋다',
  },
  {
    title: 'RAG에서 Vector DB 선택 기준과 트레이드오프',
    audience: 'practitioner',
    tone: 'clear',
    length: 'long',
    rationale: '리서치와 리뷰 기준이 많은 주제라 반복 최적화가 잘 드러난다',
  },
  {
    title: 'Frontend 팀이 에이전트 평가판을 운영할 때 필요한 QA 루프',
    audience: 'beginner',
    tone: 'clear',
    length: 'medium',
    rationale: 'UX, 상태, 평가 readiness를 한 화면에서 설명하기 좋은 주제',
  },
]

export const checklistLabels = [
  'Input contract completeness',
  'Generation flow fidelity',
  'State machine completeness',
  'Error handling quality',
  'Export behavior',
  'Responsive layout',
  'Accessibility basics',
  'Visual finish',
  'Harness process adherence',
]

export const deliverables: DeliverableCard[] = [
  {
    id: 'iteration-log',
    title: 'runs/iteration_log.md',
    description: 'Minimum three writer-reviewer-optimizer loops with PASS/PARTIAL/FAIL counts.',
  },
  {
    id: 'manifest',
    title: 'runs/run_manifest.json',
    description: 'Harness name, run id, timestamps, spec version, and terminal status.',
  },
  {
    id: 'scorecard',
    title: 'reports/scorecard.json',
    description: 'Task, UX, responsiveness, a11y, process, and overall evaluation inputs.',
  },
  {
    id: 'evaluation',
    title: 'reports/evaluation_report.json',
    description: 'Combined L1/L2/L3 report generated by scripts/evaluate.py.',
  },
]

export const evaluationTargets = [
  'Expose exactly three visible loops in the app runtime.',
  'Record at least three real review/optimization passes in iteration_log.md.',
  'Reach 8 or more PASS verdicts in the last visible loop.',
  'Ship an export-ready final post and keep smoke/build/evaluation green.',
]
